import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import { getAllDevices } from '../data/devices'
import { getGreeting } from '../utils/helpers'

// Device SVG Icons
const OroScanIcon = () => (
  <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
    <rect x="11" y="2" width="10" height="8" rx="3" fill="#0d7377" opacity="0.15"/>
    <rect x="11" y="2" width="10" height="8" rx="3" stroke="#0d7377" strokeWidth="1.5" fill="none"/>
    <circle cx="16" cy="6" r="2.5" fill="#0d7377" opacity="0.3"/>
    <circle cx="16" cy="6" r="1" fill="#0d7377"/>
    <rect x="14.5" y="10" width="3" height="14" rx="1.5" fill="#0d7377" opacity="0.2"/>
    <rect x="14.5" y="10" width="3" height="14" rx="1.5" stroke="#0d7377" strokeWidth="1.5" fill="none"/>
    <path d="M14.5 24 Q14 28 12 30" stroke="#0d7377" strokeWidth="1.5" strokeLinecap="round" fill="none"/>
    <path d="M17.5 24 Q18 28 20 30" stroke="#0d7377" strokeWidth="1.5" strokeLinecap="round" fill="none"/>
  </svg>
)

const HemoCubeIcon = () => (
  <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
    <rect x="8" y="4" width="12" height="20" rx="3" fill="#ef4444" opacity="0.15"/>
    <rect x="8" y="4" width="12" height="20" rx="3" stroke="#dc2626" strokeWidth="1.5" fill="none"/>
    <rect x="11" y="8" width="6" height="4" rx="1" fill="#dc2626" opacity="0.3"/>
    <line x1="14" y1="14" x2="14" y2="20" stroke="#dc2626" strokeWidth="1.5" strokeDasharray="2 2"/>
    <circle cx="14" cy="22" r="1" fill="#dc2626"/>
  </svg>
)

const OptiHBIcon = () => (
  <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
    <circle cx="14" cy="14" r="10" fill="#f59e0b" opacity="0.12"/>
    <circle cx="14" cy="14" r="10" stroke="#d97706" strokeWidth="1.5" fill="none"/>
    <circle cx="14" cy="14" r="4" fill="#d97706" opacity="0.3"/>
    <line x1="14" y1="4" x2="14" y2="7" stroke="#d97706" strokeWidth="1.5"/>
    <line x1="14" y1="21" x2="14" y2="24" stroke="#d97706" strokeWidth="1.5"/>
    <line x1="4" y1="14" x2="7" y2="14" stroke="#d97706" strokeWidth="1.5"/>
    <line x1="21" y1="14" x2="24" y2="14" stroke="#d97706" strokeWidth="1.5"/>
  </svg>
)

const deviceIcons = {
  oroscan: { icon: <OroScanIcon />, bgColor: '#e0f2f1' },
  hemocube: { icon: <HemoCubeIcon />, bgColor: '#fef2f2' },
  optihb: { icon: <OptiHBIcon />, bgColor: '#fefce8' }
}

const TC_TEXT = [
  'This application is intended for point-of-care screening purposes only and does not provide a clinical diagnosis. All screening results are indicative and must be confirmed by a qualified healthcare professional.',
  'The operator acknowledges that screening results generated by this application are not a substitute for laboratory-grade diagnostic tests. Clinical decisions must not be based solely on the output of this application.',
  'Patient data collected through this application is stored locally on the device. The operator is responsible for ensuring data privacy and confidentiality in accordance with applicable regulations.',
  'The devices connected to this application (OroScan, HemoCube, OptiHB) must be operated as per the manufacturer guidelines. Improper device handling may lead to inaccurate results.',
  'CRTDH, IIT Kharagpur, and the development team shall not be held liable for any clinical outcomes arising from the use of screening results generated by this application.',
  'By proceeding, you confirm that you are a trained healthcare worker or authorized personnel and agree to use this application in compliance with the above terms.'
]

export default function Dashboard() {
  const navigate = useNavigate()
  const { user } = useAuth()
  const devices = getAllDevices()
  const [showTC, setShowTC] = useState(false)
  const [selectedDevice, setSelectedDevice] = useState(null)
  const [tcAccepted, setTcAccepted] = useState(false)

  const handleDeviceClick = (deviceId) => {
    // Check if T&C already accepted this session
    const accepted = sessionStorage.getItem('sclab_tc_accepted')
    if (accepted) {
      navigate(`/register/${deviceId}`)
    } else {
      setSelectedDevice(deviceId)
      setTcAccepted(false)
      setShowTC(true)
    }
  }

  const handleAcceptTC = () => {
    sessionStorage.setItem('sclab_tc_accepted', 'true')
    setShowTC(false)
    navigate(`/register/${selectedDevice}`)
  }

  return (
    <div className="dashboard">
      {/* Light header */}
      <header style={{
        padding: '20px 20px 16px',
        background: '#fff',
        borderBottom: '1px solid #e2e8f0'
      }}>
        <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center'}}>
          <div>
            <h1 style={{fontSize: '1.4rem', fontWeight: 600, color: '#1e293b', margin: 0}}>
              {getGreeting()}, {user?.name?.split(' ')[0] || 'Admin'}
            </h1>
            <p style={{fontSize: '0.85rem', color: '#64748b', margin: '4px 0 0'}}>
              Select a device to begin screening
            </p>
          </div>
          <div style={{display: 'flex', alignItems: 'center', gap: 8}}>
            <img
              src="./images/logos/iitkgp_logo.png"
              alt="IIT Kharagpur"
              style={{ width: 36, height: 36, objectFit: 'contain' }}
            />
            <img
              src="./images/logos/crtdh_logo.png"
              alt="CRTDH"
              style={{ width: 40, height: 40, objectFit: 'contain' }}
            />
          </div>
        </div>
      </header>

      {/* Device cards */}
      <main style={{padding: 20}}>
        <div style={{display: 'flex', flexDirection: 'column', gap: 12}}>
          {devices.map((device) => {
            const info = deviceIcons[device.id] || deviceIcons.hemocube
            return (
              <div
                key={device.id}
                className="device-card"
                onClick={() => handleDeviceClick(device.id)}
                role="button"
                tabIndex="0"
                style={{
                  background: '#fff', borderRadius: 16, padding: 20,
                  display: 'flex', alignItems: 'center', gap: 16,
                  boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
                  border: '1px solid #f1f5f9',
                  cursor: 'pointer', transition: 'transform 0.15s ease'
                }}
              >
                <div style={{
                  width: 56, height: 56, borderRadius: 14,
                  backgroundColor: info.bgColor,
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  flexShrink: 0
                }}>
                  {info.icon}
                </div>
                <div style={{flex: 1, minWidth: 0}}>
                  <h2 style={{fontSize: '1.05rem', fontWeight: 600, color: '#1e293b', margin: 0}}>
                    {device.name}
                  </h2>
                  <p style={{fontSize: '0.82rem', color: '#64748b', margin: '3px 0 0', lineHeight: 1.4}}>
                    {device.description}
                  </p>
                </div>
                <span style={{color: '#94a3b8', fontSize: '1.4rem', fontWeight: 300, flexShrink: 0}}>›</span>
              </div>
            )
          })}
        </div>
      </main>

      {/* T&C Bottom Sheet Modal */}
      {showTC && (
        <div
          style={{
            position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
            background: 'rgba(0,0,0,0.45)', zIndex: 2000,
            display: 'flex', alignItems: 'flex-end', justifyContent: 'center',
            animation: 'fadeIn 0.2s ease-out'
          }}
          onClick={() => setShowTC(false)}
        >
          <div
            style={{
              width: '100%', maxWidth: 480, maxHeight: '85vh',
              background: '#fff', borderRadius: '20px 20px 0 0',
              display: 'flex', flexDirection: 'column',
              animation: 'slideUp 0.3s ease-out'
            }}
            onClick={(e) => e.stopPropagation()}
          >
            {/* Handle bar */}
            <div style={{display:'flex', justifyContent:'center', padding: '12px 0 4px'}}>
              <div style={{width: 36, height: 4, borderRadius: 2, background: '#e2e8f0'}}/>
            </div>

            {/* Header */}
            <div style={{padding: '8px 20px 16px', borderBottom: '1px solid #f1f5f9'}}>
              <div style={{display:'flex', alignItems:'center', gap: 10}}>
                <div style={{
                  width: 36, height: 36, borderRadius: 10,
                  background: '#e0f2f1', display:'flex', alignItems:'center', justifyContent:'center'
                }}>
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#0d7377" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                    <polyline points="14 2 14 8 20 8"/>
                    <line x1="16" y1="13" x2="8" y2="13"/>
                    <line x1="16" y1="17" x2="8" y2="17"/>
                    <polyline points="10 9 9 9 8 9"/>
                  </svg>
                </div>
                <div>
                  <h2 style={{margin: 0, fontSize: '1.05rem', fontWeight: 600, color: '#1e293b'}}>Terms & Conditions</h2>
                  <p style={{margin: '2px 0 0', fontSize: '0.75rem', color: '#94a3b8'}}>Please read before proceeding</p>
                </div>
              </div>
            </div>

            {/* Scrollable T&C content */}
            <div style={{
              flex: 1, overflowY: 'auto', padding: '16px 20px',
              maxHeight: '45vh'
            }}>
              {TC_TEXT.map((clause, i) => (
                <div key={i} style={{
                  display: 'flex', gap: 10, marginBottom: 14,
                  fontSize: '0.8rem', color: '#475569', lineHeight: 1.6
                }}>
                  <span style={{
                    flexShrink: 0, width: 20, height: 20, borderRadius: 6,
                    background: '#f7f9fc', border: '1px solid #e2e8f0',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontSize: '0.65rem', fontWeight: 600, color: '#94a3b8', marginTop: 2
                  }}>
                    {i + 1}
                  </span>
                  <span>{clause}</span>
                </div>
              ))}
            </div>

            {/* Checkbox + Proceed */}
            <div style={{
              padding: '16px 20px', borderTop: '1px solid #f1f5f9',
              paddingBottom: 'calc(16px + env(safe-area-inset-bottom, 0px))'
            }}>
              <label style={{
                display: 'flex', alignItems: 'flex-start', gap: 10,
                cursor: 'pointer', marginBottom: 14
              }}>
                <input
                  type="checkbox"
                  checked={tcAccepted}
                  onChange={(e) => setTcAccepted(e.target.checked)}
                  style={{
                    width: 20, height: 20, flexShrink: 0, marginTop: 1,
                    accentColor: '#0d7377', cursor: 'pointer'
                  }}
                />
                <span style={{fontSize: '0.82rem', color: '#1e293b', lineHeight: 1.5}}>
                  I have read and agree to the Terms & Conditions
                </span>
              </label>
              <button
                onClick={handleAcceptTC}
                disabled={!tcAccepted}
                style={{
                  width: '100%', padding: '14px',
                  background: tcAccepted ? '#0d7377' : '#cbd5e1',
                  border: 'none', borderRadius: 14,
                  color: '#fff', fontSize: '0.95rem', fontWeight: 600,
                  cursor: tcAccepted ? 'pointer' : 'not-allowed',
                  transition: 'all 0.2s ease'
                }}
              >
                Proceed
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
